export GOPACKAGESDEBUG=1

00:
	go run $(shell echo $@*/)main.go golang.org/x/tools/go/packages
01:
	go run $(shell echo $@*/)main.go golang.org/x/tools/go/packages
# full ast
02:
	go run $(shell echo $@*/)main.go m/internal/s
