# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
)


class S(Schema):
    xs = fields.List(fields.Nested(lambda: SXsItem()))
    ys = fields.List(fields.Nested(lambda: O()))


class SXsItem(Schema):
    name = fields.String()


class O(Schema):
    name = fields.String()
