# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields,
)


class S(Schema):
    xs = fields.List(fields.String())
    ys = fields.List(fields.String())
    zs = fields.Nested(fields.List(many=True))
