# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
)


class S(Schema):
    x = fields.Dict(keys=fields.String(), values=fields.Integer())
    y = fields.Dict(keys=fields.String(), values=fields.Nested(lambda: P()))
    z = fields.Dict(keys=fields.String(), values=fields.Integer())
