# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
)


class S(Schema):
    x = fields.Dict(keys=fields.String(), values=fields.Nested(lambda: SX__additionalProperties()))
    y = fields.Dict(keys=fields.String(), values=fields.Nested(lambda: O()))
    z = fields.Dict(keys=fields.String(), values=fields.Nested(lambda: D__additionalProperties()))


class SX__additionalProperties(Schema):
    name = fields.String()


class O(Schema):
    name = fields.String()


class D__additionalProperties(Schema):
    name = fields.String()
