# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields,
)


class S(Schema):
    x = fields.Nested(lambda: S)
    y = fields.Nested(lambda: Y)


class Y(S):
    pass
