# this is auto-generated by swagger-marshmallow-codegen
from __future__ import annotations
from marshmallow import (
    Schema,
    fields,
)


class S(Schema):
    x = fields.Nested(lambda: SX())
    y = fields.Nested(lambda: O())


class SX(Schema):
    name = fields.String()


class O(Schema):
    name = fields.String()
