# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields,
)


class S(Schema):
    x = fields.Field()
    y = fields.Nested(lambda: O)


class O(Schema):
    name = fields.String()
