00:
	python $@*.py
	mypy --strict $@*.py
01:
	python $@*.py
	mypy --strict $@*.py
02:
	python $@*.py
	mypy --strict $@*.py
03:
	python $@*.py
	mypy --strict $@*.py
04:
	python $@*.py
	mypy --strict $@*.py
05:
	python $@*.py
	mypy --strict $@*.py
06:
	python $@*.py
	mypy --strict $@*.py
07:
	python $@*.py
	mypy --strict $@*.py
