00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python -m libcst.tool print 02*.py | tee $@.output
04:
	python $(shell echo $@*.py)
05:
	python $(shell echo $@*.py)
06:
	python $(shell echo $@*.py)
07:
	python $(shell echo $@*.py)
