00:
	LOGGING_FORMAT="pid=%(process)s	relative=%(relativeCreated).2f	message:%(message)s" DEBUG=1 python $(shell echo $@*.py) run
01:
	LOGGING_FORMAT="pid=%(process)s	relative=%(relativeCreated).2f	message:%(message)s" DEBUG=1 python $(shell echo $@*.py) run
