default:
	dictknife diff 00.json 01.json
	dictknife diff 00.json 01.json -o dict
	dictknife diff 00.json 01.json -o dict | dictknife cat -i json -o md
	dictknife diff 00.json 01.json -o md
	dictknife diff 00.json 01.json -o md --skip-empty
