# graphql-core-next (sync)
01:
	python $@*/main.py
# graphql-core-next (async)
02:
	python $@*/main.py
# graphene
03:
	python $@*/main.py
# ariadne with asyncio test
04:
	pytest --show-capture=all  -vv $@*/test*.py
05:
	pytest --show-capture=all -vv $@*/test*.py
# ariadne
06:
	python $@*/main.py
