01:
	mkdir -p dst
	python 01pyramid.py > dst/01pyramid.dot
	dot -Tsvg dst/01pyramid.dot > dst/01pyramid.svg

02:
	mkdir -p dst
	python 02pyramid.py > dst/02pyramid.dot
	dot -Tsvg dst/02pyramid.dot > dst/02pyramid.svg

04:
	mkdir -p dst
	python 04pyramid.py > dst/04pyramid.dot
	dot -Tsvg dst/04pyramid.dot > dst/04pyramid.svg
