default:
	zenmai template.yaml --data "data.yaml#/app/local" | nejimaki --position=dist
	zenmai template.yaml --data "data.yaml#/app/dev" | nejimaki --position=dist
	zenmai template.yaml --data "data.yaml#/app/production" | nejimaki --position=dist
