00:
	python $(shell echo $@*.py)

# named pipe
01:
	DEBUG=1 python $(shell echo $@*.py) run

# multi worker
02:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run

# send/recv action
03:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run

# wrapper object
04:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run

# jsonrpc
05:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# minitask
06:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# minitask + transformer
07:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# minitask2
08:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# bidirectional
09:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# executor
10:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# threading
11:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# use handofcats indirectly
12:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# fake producer
13:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# fake consumer
14:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# fake consumer and producer
15:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# use minitask3, fake
16:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# use minitask3, command (threading)
17:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
# bot simuration
18:
	LOGGING_FORMAT="%(levelname)s	%(process)s	%(message)s" DEBUG=1 python $(shell echo $@*.py) run
