00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)
04:
	python $(shell echo $@*.py)
05:
	mypy --strict $(shell echo $@*.py)
06:
	mypy --strict $(shell echo $@*.py)
	# python $(shell echo $@*.py)
07:
	# LOGGING_LEVEL=INFO LOGGING_TIME=relative DEBUG=1 python $(shell echo $@*.py)
	python $(shell echo $@*.py)
