package main

import (
	"flag"
	"os"
	"log"
	"fmt"
)

// this file is generated by egoist.generators.clikit

// Option ...
type Option struct {
	Nickname string // for `-nickname`
	Args []string // cmd.Args
}


func main() {
	opt := &Option{}
	cmd := flag.NewFlagSet("byebye", flag.ContinueOnError)

	cmd.StringVar(&opt.Nickname, "nickname", "", "-")

	if err := cmd.Parse(os.Args[1:]); err != nil {
		if err != flag.ErrHelp {
			cmd.Usage()
		}
		os.Exit(1)
	}
	opt.Args = cmd.Args()
	if err := run(opt); err != nil {
		log.Fatalf("!!%+v", err)
	}
}

func run(opt *Option) error {
	// generated by `with runtime.generate(clikit): ...`
	// runtime.generate() is not called, please use it
	fmt.Printf("not implemented yet\n")
	return nil
}