00:
	python logged.py 00*.py
01:
	python logged.py 01*.py
02:
	python logged.py dictknife cat a.json
03:
	python logged.py -m tokenize logged.py
04:
	python logged.py --loggedpy-driver=./customized.py:Driver 00*.py
05:
	python logged.py --loggedpy-driver=./customized.py:Driver 01*.py
06:
	python logged.py --loggedpy-driver=./customized.py:Driver dictknife cat a.json
07:
	python logged.py --loggedpy-driver=./customized.py:Driver -m tokenize logged.py
