00:
	go run $(shell echo $@*/)main$@.go --help || exit 0
# 01:
# 	go run $(shell echo $@*/)main.go --help || exit 0
02:
	go run $(shell echo $@*/)main.go --help || exit 0
	go run $(shell echo $@*/)main.go hello --help || exit 0
	go run $(shell echo $@*/)main.go hello || exit 0
03:
	go run $(shell echo $@*/)main.go --help || exit 0
	go run $(shell echo $@*/)main.go hello --help || exit 0
	go run $(shell echo $@*/)main.go hello || exit 0
04:
	go run $(shell echo $@*/)main.go --help || exit 0
	go run $(shell echo $@*/)main.go hello --help || exit 0
	go run $(shell echo $@*/)main.go hello || exit 0
05:
	go run $(shell echo $@*/)main.go  --help || exit 0
	go run $(shell echo $@*/)main.go  || exit 0
