00:
	node 00*.js
01:
	node 01*.js
02:
	node examples/photobooth/main.js
03:
	node examples/systeminfo/main.js
04:
	(cd examples/terminal && node main.js)

clone:
	(mkdir -p tmp && cd tmp && git clone --depth=1 git@github.com:GoogleChromeLabs/carlo.git && cp -r carlo/examples ../) && rm -rf tmp

