default:
	zenmai main.yaml --data "config.yaml#/version/dev" --data "config.yaml#/infra/local"
	zenmai main.yaml --data "config.yaml#/version/dev" --data "config.yaml#/infra/cloud"
	zenmai main.yaml --data "config.yaml#/version/staging" --data "config.yaml#/infra/local"
	zenmai main.yaml --data "config.yaml#/version/staging" --data "config.yaml#/infra/cloud"

