package main
import (
	"flag"
	"fmt"
	"os"
	"log"
	"m/config"
)

// this package is generated by egoist.generate.clikit

// Option ...
type Option struct {
	Config string // for `-config`
}


func main()  {
	opt := &Option{}
	cmd := flag.NewFlagSet("hello", flag.ContinueOnError)
	cmd.Usage = func(){
		fmt.Fprintln(cmd.Output(), `hello - hello message`)
		fmt.Fprintln(cmd.Output(), "")
		fmt.Fprintln(cmd.Output(), "Usage:")
		cmd.PrintDefaults()
	}
	cmd.StringVar(&opt.Config, "config", "", "-")

	if err := cmd.Parse(os.Args[1:]); err != nil {
		if err != flag.ErrHelp {
			cmd.Usage()
		}
		os.Exit(1)
	}
	if err := run(opt); err != nil {
		log.Fatalf("!!%+v", err)
	}
}

func run(opt *Option) error {
	v0, err := config.NewConfig(opt.Config)
	if err != nil  {
		return err
	}
	fmt.Println(v0.LogLevel)
	return nil
}