SHELL := bash

00:
	cd $(shell echo $@*/) && go run main.go |& tee main.output
01:
	cd $(shell echo $@*/) && go run main.go |& tee main.output
02:
	cd $(shell echo $@*/) && go run main.go |& tee main.output
04:
	cd $(shell echo $@*/) && go run main.go |& tee main.output
05:
	cd $(shell echo $@*/) && go run main.go |& tee main.output.default
	cd $(shell echo $@*/) && NAME=XXX go run main.go |& tee main.output
