consumes:
- application/json
info:
  title: Example Goswagger
  version: 0.1.0

definitions:
  id:
    type: string
    format: "[0-9a-f]{24}"
    description: id

parameters:
  id:
    name: id
    description:
      # これは無理
      $ref: "#/definitions/id"
    in: path
    type: string
    required: true

paths:
  /messages:
    get:
      operationId: messages
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: "#/definitions/id"
  /messages/{id}:
    parameters:
      - {$ref: "#/parameters/id"}
    get:
      operationId: getMessage
      responses:
        200:
          description: ok
          schema:
            type: string

produces:
- application/json
schemes:
- http
swagger: "2.0"
