00:
	python $(shell echo $@*.py) use
01:
	python $(shell echo $@*.py) use
02:
	python $(shell echo $@*.py) use
03:
	python $(shell echo $@*.py)
04:
	python $(shell echo $@*.py)
05:
	python $(shell echo $@*.py)
