00:
	python validate.py --schema 00schema.yaml --data data/person.json
01:
	python validate.py --schema 00schema.yaml --data data/person-ng.json
02:
	python validate.py --schema 00schema.yaml --data data/person-missing-name.json
03:
	python validate.py --schema 01schema.yaml --data data/person-missing-name.json
04:
	python validate.py --schema 01schema.yaml --data data/person-age-is-typo.json
05:
	python validate.py --schema 02schema.yaml --data data/person-age-is-typo.json
06:
	python validate.py --schema 02schema.yaml --data data/person-with-quota-user.json
07:
	python validate.py --schema 02schema.yaml --data data/person-with-quota-user.json
08:
	python validate.py --schema 03schema.yaml --data data/person-with-quota-user.json
09:
	python validate.py --schema 04schema.yaml --data data/person-with-parents.json
10:
	python validate.py --schema 05schema.yaml --data data/person.json
