openapi: 3.0.2
info:
  title: Swagger Petstore
  version: 1.0.0
paths:
  /pets:
    get:
      operationId: listPets
      summary: list all pets
      tags:
      - pets
      parameters:
      - name: limit
        description: How many items to return at one time (max 100)
        required: false
        schema:
          type: integer
          format: int32
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      operationId: createPets
      summary: create a pets
      tags:
      - pets
      responses:
        '201':
          description: Null response
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        tag:
          type: string
      required:
      - id
      - name
