00:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml
# with parameters
01:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml

# with parameters, use body
02:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml

# omit 200
03:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml

# path
04:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml

# default error response
05:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml

# extra header
06:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml

# misc (info.license, servers)
07:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml

# new type
08:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml

# extra data
09:
	python $(shell echo $@*.py) | tee $(shell echo $@*.py).yaml
