00:
	python $(shell echo $@*.py)
# with parameters
01:
	python $(shell echo $@*.py)

# with parameters, use body
02:
	python $(shell echo $@*.py)

# omit 200
03:
	python $(shell echo $@*.py)

# path
04:
	python $(shell echo $@*.py)

# default error response
05:
	python $(shell echo $@*.py)

# extra header
06:
	python $(shell echo $@*.py)

#
07:
	python $(shell echo $@*.py)
