default:
	yapf base.py > base.yapf.py
	yayapf base.py > base.yayapf.py
	yapf base2.py > base2.yapf.py
	yayapf base2.py > base2.yayapf.py
	yapf base3.py > base3.yapf.py
	yayapf base3.py > base3.yayapf.py
	yapf base4.py > base4.yapf.py
	yayapf base4.py > base4.yayapf.py
