SHELL := $(shell which bash)
default: 000 001 002 003 004 005 006 007 008 009 010 011 012 013 014 015 016 017 018 019 020 021 022 023 024 025 026 027 028 029 030 031 032 033 034 035 036 037 038 039 040 041 042 043 044 045 046 047 048 049 050 051 052 053 054 055 056 057 058 059 060 061 062 063 064 065 066 067 068 069 070 071 072 073 074 075 076 077 078 079 080 081 082 083 084 085 086 087 088 089 090 091 092 093 094 095 096 097 098 099 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 
000:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
001:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
002:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
003:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
004:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
005:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
006:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
007:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
008:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
009:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
010:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
011:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
012:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
013:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
014:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
015:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
016:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
017:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
018:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
019:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
020:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
021:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
022:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
023:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
024:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
025:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
026:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
027:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
028:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
029:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
030:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
031:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
032:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
033:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
034:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
035:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
036:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
037:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
038:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
039:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
040:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
041:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
042:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
043:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
044:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
045:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
046:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
047:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
048:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
049:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
050:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
051:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
052:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
053:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
054:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
055:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
056:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
057:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
058:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
059:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
060:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
061:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
062:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
063:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
064:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
065:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
066:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
067:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
068:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
069:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
070:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
071:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
072:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
073:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
074:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
075:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
076:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
077:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
078:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
079:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
080:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
081:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
082:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
083:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
084:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
085:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
086:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
087:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
088:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
089:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
090:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
091:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
092:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
093:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
094:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
095:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
096:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
097:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
098:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
099:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
100:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
101:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
102:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
103:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
104:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
105:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
106:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
107:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
108:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
109:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
110:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
111:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
112:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
113:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
114:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
115:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
116:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
117:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
118:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
119:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
120:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
121:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
122:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
123:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
124:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
125:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
126:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
127:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
128:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))
129:
	python $(shell echo code$@.py) |& tee $(patsubst %.py,%.svg,$(shell echo code$@.py))