00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	DEBUG=1 LOGGING_TIME=relative python $(shell echo $@*.py) main_list_comprehension -n 3
	@echo ----------------------------------------
	DEBUG=1 LOGGING_TIME=relative python $(shell echo $@*.py) main_gather -n 3
