00:
	go run $@*/main.go
01:
	go run $@*/main.go
02:
	go run $@*/main.go
03:
	go run $@*/main.go
04:
	go run $@*/main.go
05:
	go run $@*/main.go
06:
	go run $@*/main.go
07:
	go run $@*/main.go
08:
	go run $@*/main.go
