## bundle
00:
	jsonknife bundle --src 00*/main.yaml
01:
	jsonknife bundle --src 00*/person.yaml --ref "#/definitions/people"

## json2swagger
02:
	swaggerknife json2swagger 02*/data.json
03:
	swaggerknife json2swagger 03*/data.json
