00:
	python $(shell echo $@*.py)
	mypy --strict $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
	mypy --strict $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
	mypy --strict $(shell echo $@*.py)
