00:
	python $@*.py
01:
	python $@*.py
02:
	python $@*.py
03:
	python $@*.py
04:
	python $@*.py
07:
	pycomment --inplace $@*.py
08:
	pycomment --inplace $@*.py
09:
	python $@*.py
setup:
	pip install -r requirements.txt
