00:
	dart $(shell echo $@*.dart)
01:
	dart $(shell echo $@*.dart)
02:
	dart $(shell echo $@*.dart)
03:
	dart $(shell echo $@*.dart)
04:
	pub run test $(shell echo $@*/)
05:
	dart $(shell echo $@*.dart)
06:
	dart $(shell echo $@*.dart)
07:
	dart $(shell echo $@*.dart)
