default: 00 01 02 03 04
00:
	dictknife cat -i spreadsheet -o json "1BPLY4-IQ0k9PC2TVa8p08twtQZmGeZ663CKV5wAD8_I" | tee 00.json
01:
	dictknife cat -i spreadsheet -o json "1BPLY4-IQ0k9PC2TVa8p08twtQZmGeZ663CKV5wAD8_I#/seasons!A1:B" | tee 01.json
02:
	dictknife cat -i spreadsheet -o json "1BPLY4-IQ0k9PC2TVa8p08twtQZmGeZ663CKV5wAD8_I#/months" | tee 02.json
03:
	dictknife cat -i spreadsheet -o json "https://docs.google.com/spreadsheets/d/1BPLY4-IQ0k9PC2TVa8p08twtQZmGeZ663CKV5wAD8_I/edit#gid=2030707906" | tee 03.json
04:
	dictknife cat -i spreadsheet -o json "https://docs.google.com/spreadsheets/d/1BPLY4-IQ0k9PC2TVa8p08twtQZmGeZ663CKV5wAD8_I/edit?ranges=seasons!A1:B#gid=2040707906" | tee 04.json
