00:
	python 00*.py | tee 00.tsv
01:
	cat 00.tsv | python 01*.py | tee 010.output
	cat 00.tsv | python 01*.py | tee 011.output
	cat 00.tsv | python 01*.py | tee 012.output

02:
	cat 00.tsv | python 02*.py | tee 020.output
	cat 00.tsv | python 02*.py | tee 021.output
	cat 00.tsv | python 02*.py | tee 022.output
