setup:
	pip install -r requirementst.xt
00:
	python 00*.py
01:
	python 01*.py
02:
	python 02*.py
03:
	python 03*.py
04:
	python 04*.py
05:
	python 05*.py
06:
	python 06*.py
07:
	python 07*.py
08:
	python 08*.py
