package foo

import (
	"fmt"
)

// Code generated by "stringer -type Foo"; DO NOT EDIT.
// String :
func (x Foo) String() string {
	switch x {
	case FooFoo:
		return "foo"
	case FooBar:
		return "bar"
	case FooBoo:
		return "boo"
	default:
		return fmt.Sprintf("Foo(%q)", string(x))
	}
}
