version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    volumes:
      - "$PWD/.local"
    ports:
      - "19200:9200"
      - "19300:9300"
    environment:
      - "discovery.type=single-node"
# see: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# see: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#password-security-settings

# Security note
# ----------------------------------------
# X-Pack is preinstalled in this image. Please take a few minutes to familiarize yourself with X-Pack Security and how to change default passwords. The default password for the elastic user is changem
