00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py) run
04:
	python $(shell echo $@*.py) run
05:
	python $(shell echo $@*.py) run
06:
	python $(shell echo $@*.py) run
