PYTHON ?= LOGLEVEL=DEBUG PYTHONASYNCIODEBUG=1 python -W default

00:
	time ${PYTHON} 00*.py
01:
	time ${PYTHON} 01*.py
02:
	time ${PYTHON} 02*.py
03:
	time ${PYTHON} 03*.py
04:
	time ${PYTHON} 04*.py
07:
	time ${PYTHON} 07*.py
