type: object
properties:
  port:
    type: integer
  logLevel:
    enum:
    - debug
    - info
    - warn
    - error
    - critical
  xxxAPI:
    $ref: '#/definitions/XXXAPI'
required:
- port
- logLevel
definitions:
  XXXAPI:
    type: object
    properties:
      name:
        type: string
        minLength: 1
    required:
    - name
