00:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
01:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
02:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
