00:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
01:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
02:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
03:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
04:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
05:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
06:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
07:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
08:
	go run $(shell echo $@*/)main.go | tee $(shell echo $@*/)output.txt
