package model

import (
	"github.com/podhmo/maperr"
	"encoding/json"
)

// this file is generated by egoist.generators.structkit

type Person struct {
	Name string `json:"name"`
	Age int `json:"age"`
	Father *Person `json:"father"`
	Mother *Person `json:"mother"`
	Children []Person `json:"children"`
	Followings []*Person `json:"followings"`
}

func (p *Person) UnmarshalJSON(b []byte) error {
	var err *maperr.Error

	// loading internal data
	var inner struct {
		Name *string `json:"name"`// required
		Age *int `json:"age"`// required
		Father *json.RawMessage `json:"father"`
		Mother *json.RawMessage `json:"mother"`
		Children *json.RawMessage `json:"children"`// required
		Followings *json.RawMessage `json:"followings"`// required
	}
	if rawErr := json.Unmarshal(b, &inner); rawErr != nil  {
		return err.AddSummary(rawErr.Error())
	}

	// binding field value and required check
	{
		if inner.Name != nil  {
			p.Name = *inner.Name
		} else  {
			err = err.Add("name", maperr.Message{Text: "required"})
		}
		if inner.Age != nil  {
			p.Age = *inner.Age
		} else  {
			err = err.Add("age", maperr.Message{Text: "required"})
		}
		if inner.Father != nil  {
			p.Father = &Person{}
			if rawerr := json.Unmarshal(*inner.Father, p.Father); rawerr != nil  {
				err = err.Add("father", maperr.Message{Error: rawerr})
			}
		}
		if inner.Mother != nil  {
			p.Mother = &Person{}
			if rawerr := json.Unmarshal(*inner.Mother, p.Mother); rawerr != nil  {
				err = err.Add("mother", maperr.Message{Error: rawerr})
			}
		}
		if inner.Children != nil  {
			p.Children = []Person{}
			if rawerr := json.Unmarshal(*inner.Children, &p.Children); rawerr != nil  {
				err = err.Add("children", maperr.Message{Error: rawerr})
			}
		} else  {
			err = err.Add("children", maperr.Message{Text: "required"})
		}
		if inner.Followings != nil  {
			p.Followings = []*Person{}
			if rawerr := json.Unmarshal(*inner.Followings, &p.Followings); rawerr != nil  {
				err = err.Add("followings", maperr.Message{Error: rawerr})
			}
		} else  {
			err = err.Add("followings", maperr.Message{Text: "required"})
		}
	}

	return err.Untyped()
}