00:
	go test ./$(shell echo $@*/)
01:
	go test ./$(shell echo $@*/)
02:
	# error
	# go run ./$(shell echo $@*/)main.go
	go test -tags mock ./$(shell echo $@*/)
03:
	# error
	# go run ./$(shell echo $@*/)main.go
	go test -tags mock ./$(shell echo $@*/)
