# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields
)


class Bridge(Schema):
    name = fields.String(required=True)
    username = fields.String(required=True)
    port = fields.Integer(required=True)
    pin = fields.String(required=True)


class AccessoriesItem(Schema):
    accessory = fields.String(required=True)
    name = fields.String(required=True)


class PlatformsItem(Schema):
    platform = fields.String(required=True)
    name = fields.String(required=True)


class Conf(Schema):
    bridge = fields.Nested('Bridge', required=True)
    description = fields.String(required=True)
    accessories = fields.List(fields.Nested('AccessoriesItem'), required=True)
    platforms = fields.List(fields.Nested('PlatformsItem'), required=True)
