00:
	python -m monogusa.cli $@*.py hello --name=world
	python -m monogusa.cli $@*.py bye --name=bye
01:
	python -m monogusa.cli $@*.py -h
02:
	python -m monogusa.cli $@*.py hello
	DEBUG=1 python -m monogusa.cli $@*.py hello
