00:
	go run $(shell echo $@*)/main.go
01:
	go run $(shell echo $@*)/main.go
02:
	go run $(shell echo $@*)/main.go
03:
	DEBUG=1 go run $(shell echo $@*)/main.go
04:
	DEBUG=1 go run $(shell echo $@*)/main.go
05:
	DEBUG=1 go run $(shell echo $@*)/main.go
06:
	DEBUG=1 go run $(shell echo $@*)/main.go
