PORT ?= 8888

# echo {"title": "hello"} | http --json POST :8888/todos
# echo '{"title": "hello"}' | http --json POST :8888/todos
# echo '{"titleee": "hello"}' | http --json POST :8888/todos
00:
	uvicorn $(patsubst %.py,%,$(shell echo $@*.py)):app --port $(PORT)
01:
	uvicorn $(patsubst %.py,%,$(shell echo $@*.py)):app --port $(PORT)
02:
	uvicorn $(patsubst %.py,%,$(shell echo $@*.py)):app --port $(PORT)
03:
	uvicorn $(patsubst %.py,%,$(shell echo $@*.py)):app --port $(PORT)
