00:
	mypy --strict $(shell echo $@*.py)
01:
	mypy --strict $(shell echo $@*.py)
02:
	mypy --strict $(shell echo $@*.py)
03:
	mypy --strict $(shell echo $@*.py)
04:
	mypy --strict $(shell echo $@*.py)

