00:
	python 00dump.py --format json person.json
	python 00dump.py --format toml person.json
	python 00dump.py --format json --extra--sort-keys person.json
	python 00dump.py --format toml --extra--sort-keys  person.json

01:
	python 01dump.py -h || echo ""
	python 01dump.py --format json --extra--sort-keys person.json
	python 01dump.py --format toml person.json

03:
	python 03dump.py -h || echo ""
	python 03dump.py --format json --extra--sort-keys person.json
	python 03dump.py --format toml --extra--sort-keys person.json
