export DEBUG := 1

00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)
04:
	mypy --strict $(shell echo $@*.py)
05:
	python $(shell echo $@*/)main.py
	mypy --strict $(shell echo $@*/)main.py

