00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)
04:
	python $(shell echo $@*.py)
05:
	python $(shell echo $@*.py)
06:
	python $(shell echo $@*.py)
07:
	python $(shell echo $@*.py)
08:
	python $(shell echo $@*.py)
09:
	python $(shell echo $@*.py)
