serve:
	python -m reqtrace.commands.echo --port 44444 --pretty

py: 00 01 02 03

00:
	python 00*.py | tee 00.output
01:
	python 01*.py | tee 01.output
02:
	python 02*.py | tee 02.output
03:
	python 03*.py | tee 03.output
04:
	python 04*.py | tee 04.output
