00:
	DEBUG=1 python $@*.py master
01:
	DEBUG=1 python $@*.py master
02:
	LOGGING_FORMAT="%(process)d	%(message)s	%(relativeCreated)s	" DEBUG=1 python $@*.py master
03:
	LOGGING_FORMAT="%(process)d	%(message)s	%(relativeCreated)s	" DEBUG=1 python $@*.py master
04:
	DEBUG=1 python $@*.py main
