INSERT INTO groups VALUES(1, "A");
INSERT INTO groups VALUES(2, "B");
INSERT INTO groups VALUES(3, "C");

INSERT INTO users VALUES(10, 1, "Ax");
INSERT INTO users VALUES(11, 1, "Ay");
INSERT INTO users VALUES(20, 2, "Bi");
INSERT INTO users VALUES(40, 4, "D?");
