CREATE TABLE groups (
   gid INTEGER PRIMARY KEY AUTOINCREMENT,
   gname TEXT NOT NULL
);

CREATE TABLE users (
   uid INTEGER PRIMARY KEY AUTOINCREMENT,
   gid INTEGER NOT NULL,
   uname TEXT NOT NULL,
   FOREIGN KEY(gid) REFERENCES groups(uid)
);
