00:
	DEBUG=1 python $(shell echo $@*.py)
01:
	DEBUG=1 python $(shell echo $@*.py)
02:
	DEBUG=1 python $(shell echo $@*.py)

10:
	docker build -t foo:0.0.0 .
11:
	docker build -t foo:0.1.0 . -f Dockerfile.multi
