bundle:
	deno run -A ~/ghq/github.com/podhmo/deno-glue/main.ts bundle --output-style html --next --development ./client.tsx | tee index.html
serve:
	deno run -A ~/ghq/github.com/podhmo/deno-glue/main.ts serve --port 8080 app.ts --next --development