00:
	cd $(shell echo $@*/) && python -m monogusa.web commands.py
	python $@*/web.py
# dictknife mkdict name=world |  http --json POST :55555/hello
# http --json POST :55555/byebye

01:
	cd $(shell echo $@*/) && python -m monogusa.web commands.py
	python $@*/web.py
# http --json POST :55555/must_error

