version: 2
jobs:
  build-python27:
    docker:
      - image: python:2.7.13
    working_directory: ~/your_project
    steps:
      - run: echo "hello python 2.7.13"
  build-python35:
    docker:
      - image: python:3.5.3
    working_directory: ~/your_project
    steps:
      - run: echo "hello python 3.5.3"
  build-python36:
    docker:
      - image: python:3.6.0
    working_directory: ~/your_project
    steps:
      - run: echo "hello python 3.6.0"

workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python35
      - build-python36
