default: one two three

one:
	python -c 'import sys; print(sys.argv); sys.exit(0)' 1
two:
	python -c 'import sys; print(sys.argv); sys.exit(1)' 2
three:
	python -c 'import sys; print(sys.argv); sys.exit(0)' 3
