# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields
)


class Person(Schema):
    name = fields.String(required=True)
    age = fields.Integer(required=True)
    nick_name = fields.String(dump_to='nickName', load_from='nickName')
