00:
	python 00*.py person.json
01:
	python 00*.py person2.json
02:
	python 01*.py person2.json
03:
	python 03*.py person2.json
04:
	python 04*.py person2.json
05:
	python 05*.py person2.json
06:
	python 06*.py person2.json
07:
	python 07*.py person2.json
