00:
	python -m monogusa.cli commands.py hello
01:
	python -m monogusa.web commands.py
	python web.py --show-doc
02:
	cd $(shell echo $@*/) && python -m monogusa.web commands.py
	python $(shell echo $@*/)web.py --show-doc
