FILE ?= petstore-minimal.yaml

00:
	python $(shell echo $@*.py) --filename $(FILE)

petstore-minimal.yaml:
	wget https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore-minimal.yaml
