default: 00 01 02 03 04 05 06 07

00:
	cat $(shell echo $@*.sql) | sqlite3 -line | tee $@.output
01:
	cat $(shell echo $@*.sql) | sqlite3 -line | tee $@.output
02:
	cat $(shell echo $@*.sql) | sqlite3 -line | tee $@.output
03:
	cat $(shell echo $@*.sql) | sqlite3 -line | tee $@.output
04:
	cat $(shell echo $@*.sql) | sqlite3 -line | tee $@.output
05:
	cat $(shell echo $@*.sql) | sqlite3 -line | tee $@.output
06:
	cat $(shell echo $@*.sql) | sqlite3 -column | tee $@.output
07:
	cat $(shell echo $@*.sql) | sqlite3 -line | tee $@.output
