00:
	go run $(shell echo $@*/)main.go
01:
	go run $(shell echo $@*/)main.go
02:
	go run $(shell echo $@*/)main.go
03:
	go run $(shell echo $@*/)main.go
04:
	cd $(shell echo $@*/) && go test
05:
	cd $(shell echo $@*/) && go test
06:
	cd $(shell echo $@*/) && go test
07:
	cd $(shell echo $@*/) && go test
