00:
	go run $(shell echo $@*/)main.go
01:
	go run $(shell echo $@*/)main.go
02:
	go run $(shell echo $@*/)main.go
03:
	go run $(shell echo $@*/)main.go
04:
	cd $(shell echo $@*/) && go test
05:
	cd $(shell echo $@*/) && go test
06:
	cd $(shell echo $@*/) && go test
07:
	cd $(shell echo $@*/) && go test
08:
	cd $(shell echo $@*/) && go test
09:
	echo $(shell echo $@*/)main.go
10:
	go run $(shell echo $@*/)main.go
11:
	go run $(shell echo $@*/)main.go
12:
	go run $(shell echo $@*/)main.go
13:
	go run $(shell echo $@*/)main.go
14:
	go run $(shell echo $@*/)main.go
15:
	go run $(shell echo $@*/)main.go
