00:
	python -u $(shell echo $@*.py) 2>&1 | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
01:
	python -u $(shell echo $@*.py) 2>&1 | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
02:
	python -u $(shell echo $@*.py)
03:
	python -u $(shell echo $@*.py) 2>&1 | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
04:
	python -u $(shell echo $@*.py) 2>&1 | tee $(patsubst %.py,%.output,$(shell echo $@*.py))

