00:
	python $(shell echo $@*.py)
01:
	python $(shell echo 00*.py) | grep "^@" | cut -d " " -f 4 | sort | uniq -c | sort
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)	
04:
	python $(shell echo $@*.py)		
05:
	python $(shell echo $@*.py)