# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields
)
from swagger_marshmallow_codegen.schema import PrimitiveValueSchema
import re
from marshmallow.validate import Regexp


class UsersUserIdEmailsInput(object):
    class Get(object):
        """
        emails
        """

        class Path(Schema):
            userId = fields.String(description='user id.')


class UsersUserIdEmailsOutput(object):
    class Get200(PrimitiveValueSchema):
        v = fields.String(validate=[Regexp(regex=re.compile('.+@.+'))])
