paths:
  /ints:
    get:
      responses:
        200:
          description: ok
          schema:
            items:
              type: integer
    post:
      parameters:
        - description: ints.
          in: body
          name: body
          schema:
            type: array
            items:
              type: integer
