SHELL := bash

00:
	go run $(shell echo $@*/)main.go testdata/api_alerting.go.data |& tee $(shell echo $@*/)output.txt
01:
	go run $(shell echo $@*/)main.go testdata/api_alerting.go.data |& tee $(shell echo $@*/)output.txt
02:
	go run $(shell echo $@*/)main.go testdata/api_alerting.go.data |& tee $(shell echo $@*/)output.txt
03:
	go run $(shell echo $@*/)main.go testdata/api_alerting.go.data | tee $(shell echo $@*/)output.yml
