00:
	pytest $(shell echo $@*/) -s
01:
	cd $(shell echo $@*/) && pytest -s
02:
	cd $(shell echo $@*/) && pytest -s
03:
	cd $(shell echo $@*/) && pytest -s
04:
	cd $(shell echo $@*/) && pytest -s
05:
	cd $(shell echo $@*/) && pytest -s -v
setup:
	pip install -U starlette pytest
