00:
	DEBUG=1 LOGGING_LEVEL=INFO LOGGING_FORMAT="%(process)s	%(relativeCreated).2f	%(levelname)s:%(message)s" python $(shell echo $@*.py)
01:
	DEBUG=1 LOGGING_LEVEL=INFO LOGGING_FORMAT="%(process)s	%(relativeCreated).2f	%(levelname)s:%(message)s" python $(shell echo $@*.py)
02:
	DEBUG=1 LOGGING_LEVEL=INFO LOGGING_FORMAT="%(process)s	%(relativeCreated).2f	%(levelname)s:%(message)s" python $(shell echo $@*.py)
03:
	DEBUG=1 LOGGING_LEVEL=INFO LOGGING_FORMAT="%(process)s	%(relativeCreated).2f	%(levelname)s:%(message)s" python $(shell echo $@*.py)
