00:
	echo '{"title": "00", "cmd": "python 00*.py"}' | kamidana -i json example.md.j2 -a reader | tee 00.md
01:
	echo '{"title": "01", "cmd": "python 01*.py"}' | kamidana -i json example.md.j2 -a reader | tee 01.md
