00:
	go run $(shell echo $@*/)main.go data.txt  data.txt
01:
	go run $(shell echo $@*/)main.go data.txt  data.txt
02:
	go run $(shell echo $@*/)main.go data.txt xx  data.txt
03:
	go run $(shell echo $@*/)main.go data.txt xx  data.txt
04:
	go run $(shell echo $@*/)main.go data.txt xx  data.txt
05:
	go run $(shell echo $@*/)main.go data.txt xx  data.txt
06:
	go run $(shell echo $@*/)main.go data.txt xx  data.txt
