00:
	python $@*.py
01:
	python $@*.py
02:
	python $@*.py
03:
	python $@*.py
04:
	python $@*.py
05:
	python $@*.py
06:
	python $@*.py
07:
	python $@*.py
08:
	python $@*.py
09:
	python $@*.py
10:
	python $@*.py
11:
	python $@*.py
