00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)
	mypy --strict $(shell echo $@*.py)
04:
	mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
05:
	mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
06:
	mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
07:
	# mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
08:
	# mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
09:
	# mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
10:
	# mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
11:
	# mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
12:
	# mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
13:
	# mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
14:
	# mypy --strict $(shell echo $@*.py)
	python $(shell echo $@*.py)
