SHELL := bash

00:
	swagger-marshmallow-codegen $(shell echo $@*/)openapi.yaml | tee $(shell echo $@*/)schema.py
01:
	swagger-marshmallow-codegen $(shell echo $@*/)openapi.yaml | tee $(shell echo $@*/)schema.py
