00:
	TITLE=emotion-example TSX=emotion.tsx deno run -A ~/ghq/github.com/podhmo/deno-glue/main.ts serve --port 8080 --next app.ts
bundle:
	deno run -A ~/ghq/github.com/podhmo/deno-glue/main.ts bundle emotion.tsx --output-style html --next | tee emotion.html
