00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)
04:
	python $(shell echo $@*.py)
05:
	python $(shell echo $@*.py)

setup:
	pip install -U -r requirements.txt
