// Code generated by sqlc. DO NOT EDIT.

package tutorial

import (
	null "gopkg.in/guregu/null.v4"
)

type Author struct {
	ID   int64       `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	Bio  null.String `db:"bio" json:"bio"`
}
