00:
	python $(shell echo $@*/)definitions.py generate_plus

01:
	python $(shell echo $@*/)definitions.py generate
02:
	python $(shell echo $@*/)definitions.py generate
03:
	python $(shell echo $@*/)definitions.py generate
