serve: websocket.py websocket.html
	python websocket.py

websocket.py:
	wget https://raw.githubusercontent.com/channelcat/sanic/master/examples/websocket.py
websocket.html:
	wget https://raw.githubusercontent.com/channelcat/sanic/master/examples/websocket.html
