PYTHON := DEBUG=1 LOGGING_LEVEL=INFO LOGGING_FORMAT="%(process)s	%(relativeCreated).2f	%(message)s" python

default: 00 01 02 03 04 05

00:
	$(PYTHON) $(shell echo $@*.py)
01:
	$(PYTHON) $(shell echo $@*.py)
02:
	$(PYTHON) $(shell echo $@*.py)
03:
	$(PYTHON) $(shell echo $@*.py)
04:
	$(PYTHON) $(shell echo $@*.py)
05:
	$(PYTHON) $(shell echo $@*.py)
