00:
	python -u $(shell echo $@*.py) | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
01:
	python -u $(shell echo $@*.py) | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
02:
	python -u $(shell echo $@*.py) | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
03:
	python -u $(shell echo $@*.py) | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
04:
	python -u $(shell echo $@*.py) | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
05:
	python -u $(shell echo $@*.py) | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
06:
	python -u $(shell echo $@*.py) | tee $(patsubst %.py,%.output,$(shell echo $@*.py))

clean:
	rm -f *.output
.PHONY: clean
