00:
	time r CMD BATCH --vanilla --slave $(shell echo $@*.r) $(shell echo $@*.r).out
01:
	time python $(shell echo $@*.py)  | tee $(shell echo $@*.py).out
02:
	time python $(shell echo $@*.py)  | tee $(shell echo $@*.py).out
