00:
	dictknife shape person.json
	dictknife shape --squash people.json

01:
	dictknife diff person.json person2.json
	dictknife diff person.json person3.json

02:
	dictknife diff person-with-skills.json person-with-skills2.json
	dictknife diff --normalize person-with-skills.json person-with-skills2.json
