03:
	python 03app.py --on=groupId data/groups.csv data/members.csv

04:
	python 04app.py --on=groupId data/groups.csv data/members.csv

05:
	python 05app.py --on=groupId data/groups.csv data/members.csv

