package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "encoding/json"

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "01server",
    "version": "0.1.0"
  },
  "paths": {
    "/person": {
      "post": {
        "description": "create person",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/person"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created",
            "schema": {
              "$ref": "#/definitions/person"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "name": {
      "type": "string",
      "minLength": 5
    },
    "person": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "age": {
          "type": "integer"
        },
        "name": {
          "$ref": "#/definitions/name"
        }
      }
    }
  }
}`))
}
