package main

import (
	"log"

	"github.com/podhmo/handwriting"
	"github.com/podhmo/handwriting/deriving"
)

func run() error {
	planner, err := handwriting.NewFromPackagePath("../01pill", handwriting.WithDryRun())
	if err != nil {
		return err
	}
	f := planner.File("pill_string.go")
	f.Header(`// Code generated by "stringer -type Pill"; DO NOT EDIT.`)
	deriving.BindStringer(f, "Pill")
	return planner.Emit()
}

func main() {
	if err := run(); err != nil {
		log.Fatalf("%+v", err)
	}
}
