dir = $(shell echo $@*)/

00:
	go run $(dir)main.go | tee $(dir)completion.bash
01:
	go run $(dir)main.go | tee $(dir)completion.bash
02:
	go run $(dir)main.go | tee $(dir)completion.bash
03:
	go run $(dir)main.go | tee $(dir)completion.bash
04:
	go run $(dir)main.go | tee $(dir)completion.bash
