00:
	go run ./$(shell echo $@*/)
01:
	go run ./$(shell echo $@*/)	
02:
	go run ./$(shell echo $@*/)	
03:
	go run ./$(shell echo $@*/)	-debug ./$(shell echo $@*/)internal/foo.go
04:
	( cd ./$(shell echo $@*/); go test -bench . )