SHELL := $(shell which bash)
PYTHON := SQLALCHEMY_WARN_20=1 python -W always::DeprecationWarning

00:
	$(PYTHON) $(shell echo $@*.py)
01:
	$(PYTHON) $(shell echo $@*.py)
02:
	$(PYTHON) $(shell echo $@*.py)
03:
	$(PYTHON) $(shell echo $@*.py)
04:
	$(PYTHON) $(shell echo $@*.py)
05:
	$(PYTHON) $(shell echo $@*.py)
06:
	$(PYTHON) $(shell echo $@*.py)
07:
	$(PYTHON) $(shell echo $@*.py)
08:
	$(PYTHON) $(shell echo $@*.py)
12:
	$(PYTHON) $(shell echo $@*.py) --name foo --data=<(echo '{"title": "go to bed"}')
13:
	$(PYTHON) $(shell echo $@*.py) --name foo --data=@data.json
