00:
	kamidana hello.j2 --data data.json | tee hello.output
02:
	kamidana hello2.j2 -a ./now.py --data data.json | tee hello2.output
03:
	kamidana hello3.j2 -a ./now.py --data data.json | tee hello3.output
