OPTS ?= -v -test.testlogfile=x.log

00:
	cd $(shell echo $@*)/ && go test $(OPTS)
01:
	cd $(shell echo $@*)/ && go test $(OPTS)
02:
	cd $(shell echo $@*)/ && go test $(OPTS)
03:
	cd $(shell echo $@*)/ && go test $(OPTS)
04:
	cd $(shell echo $@*)/ && go test $(OPTS)
05:
	cd $(shell echo $@*)/ && go test $(OPTS)
06:
	cd $(shell echo $@*)/ && go test $(OPTS)
