00:
	DEBUG=1 python $(shell echo $@*.py) run
01:
	DEBUG=1 python $(shell echo $@*.py) run
02:
	DEBUG=1 python $(shell echo $@*.py) run
03:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py) run
04:
	DEBUG=1 python $(shell echo $@*.py) run
05:
	DEBUG=1 python $(shell echo $@*.py) run
