00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	cat $(shell echo $@*messages) | python $(shell echo $@*.py)
04:
	cat $(shell echo $@*messages) | python $(shell echo $@*.py)
