// Code generated by mockery v1.0.0
package genmock

import mock "github.com/stretchr/testify/mock"

// Hello is an autogenerated mock type for the Hello type
type Hello struct {
	mock.Mock
}

// Hello provides a mock function with given fields: s
func (_m *Hello) Hello(s string) {
	_m.Called(s)
}
