01:
	pytest test_route01.py --log-cli-level=INFO -s
02:
	pytest test_route02.py --log-cli-level=INFO -s
03:
	pytest test_route03.py --log-cli-level=INFO -s

10:
	kernprof -l convert10.py
	python -m line_profiler convert10.py.lprof
11:
	kernprof -l convert11.py
	python -m line_profiler convert11.py.lprof
