00:
	go run $(shell echo $@*/)main.go
01:
	go run $(shell echo $@*/)main.go
	diff -u $(shell echo 00*/)main.go $(shell echo $@*/)main.go > $(shell echo $@*/)a.diff || exit 0

02:
	go run $(shell echo $@*/)main.go
03:
	go run $(shell echo $@*/)main.go
04:
	go run $(shell echo $@*/)main.go
05:
	go run $(shell echo $@*/)main.go
06:
	go run $(shell echo $@*/)main.go
