default: 00 01 02 03 04

00:
	PYTHONPATH=. nbreversible --format markdown --execute 00*.py > 00output.md
01:
	PYTHONPATH=. nbreversible --format markdown --execute 01*.py > 01output.md
02:
	PYTHONPATH=. nbreversible --format markdown --execute 02*.py > 02output.md
03:
	PYTHONPATH=. nbreversible --format markdown --execute 03*.py > 03output.md
04:
	PYTHONPATH=. nbreversible --format markdown --execute 04*.py > 04output.md
