site_name: hello
docs_dir: docs
theme:
  name: material
  language: 'en'
  # language: 'jp'
  # palette:
  #   primary: indigo
  #   accent: indigo

# Valid values are: red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue grey
