CMD ?= scan

00:
	cd $(shell echo $@*/) && python definitions.py $(CMD)
01:
	cd $(shell echo $@*/) && python definitions.py $(CMD)
02:
	cd $(shell echo $@*/) && python definitions.py $(CMD)
03:
	cd $(shell echo $@*/) && python definitions.py $(CMD)
