00:
	mypy --strict $@*.py
	pycomment --inplace $@*.py
01:
	mypy --strict $@*.py
	pycomment --inplace $@*.py
02:
	mypy --strict --ignore-missing-imports $@*.py
03:
	python $@*.py
04:
	mypy --strict $@*.py
05:
	mypy --strict $@*.py
06:
	python $@*.py
08:
	pytest -vv test*$@*.py
09:
	pytest -vv test*$@*.py
10:
	pytest -vv test*$@*.py
11:
	pytest -vv test*$@*.py
12:
	pytest -vv test*$@*.py
13:
	pytest -vv test*$@*.py
14:
	python $@*.py
15:
	python $@*.py
