default: 01 02

01:
	nbreversible --execute --format=markdown 01*.py > 01.md
02:
	nbreversible --execute --format=markdown 02*.py > 02.md
03:
	python -m memory_profiler 03*.py | tee 03.txt
04:
	python -m memory_profiler 04*.py | tee 04.txt
05:
	python -m memory_profiler 05*.py | tee 05.txt
06:
	python -m memory_profiler 06*.py | tee 06.txt
07:
	python -m memory_profiler 07*.py | tee 07.txt
08:
	python -m memory_profiler 08*.py | tee 08.txt
