default:
	bash -c 'python3.5 00*.py > 00py3.txt 2>&1' || exit 0
	bash -c 'python2.7 00*.py > 00py2.txt 2>&1' || exit 0
	bash -c 'python3.5 01*.py > 01py3.txt 2>&1' || exit 0
	bash -c 'python2.7 01*.py > 01py2.txt 2>&1' || exit 0

