(dolist (x (x-list-fonts "*"))
  (insert (format ";; => %s\n" x))
)

(x-list-fonts "Noto Sans CJK JP:style=Regular:slant=normal:weight=normal")

;; consoleでfc-matchで探した
(x-resolve-font-name "Noto Sans CJK JP")
;; => "-GOOG-Noto Sans CJK JP-light-normal-normal-*-*-*-*-*-*-0-iso10646-1"
(x-resolve-font-name "notosanscjkjp")
;; => "-GOOG-Noto Sans CJK JP-light-normal-normal-*-*-*-*-*-*-0-iso10646-1"


;; => "-ADBO-Source Code Pro-normal-normal-normal-*-23-*-*-*-m-0-iso10646-1"

(x-resolve-font-name "*")
;; => "-GOOG-Noto Serif CJK TC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"

 (x-resolve-font-name "notosansgothic")
;; => "-GOOG-Noto Sans Gothic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"

(x-resolve-font-name "*CJK*")

(x-resolve-font-name "Noto Sans CJK JP:style=Regular:slant=normal:weight=normal")
;; => "-GOOG-Noto Sans CJK JP-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"


;; => -GOOG-Noto Serif CJK TC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cherokee-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Marchen-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK KR-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Old Turkic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gurmukhi-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Naskh Arabic UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK TC-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-C059-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khudawadi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Serif-normal-normal-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gujarati-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mahajani-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Malayalam-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Myanmar-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK SC-semibold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Serif-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-URW Bookman-light-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Bengali-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Syriac-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Thai-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-ultrabold-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Gujarati UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Javanese-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ABAT-Cantarell-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Kufi Arabic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cham-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Georgian-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK KR-extralight-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Samaritan-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-extralight-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -PfEd-DejaVu Sans-bold-oblique-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cham-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tai Tham-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-花園明朝B-normal-normal-normal-*-*-*-*-*-d-0-iso10646-1
;; => -GOOG-Noto Serif Tibetan-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans-normal-normal-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-light-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK TC-extralight-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cham-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Armenian-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Sans-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans Mono-bold-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Mandaic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Mono PS-bold-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Kharoshthi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mongolian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mende Kikakui-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gujarati-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK JP-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Adlam Unjoined-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Telugu-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gurmukhi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Ethiopic-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bhaiksuki-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK JP-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-*-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Phoenician-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Armenian-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK SC-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Hanunoo-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Nastaliq Urdu-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-thin-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK JP-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-extralight-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Khmer-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thaana-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thaana-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Khmer-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Roman-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Old Hungarian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tibetan-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Anatolian Hieroglyphs-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cypriot-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Canadian Aboriginal-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK SC-extralight-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-URW Gothic-semibold-oblique-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Hebrew-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-URW Gothic-normal-oblique-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-normal-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Armenian-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Lao-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Khmer-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Old Italic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK HK-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ethiopic-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Hebrew-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Syriac-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Symbols2-normal-normal-ultracondensed-*-*-*-*-*-*-0-iso10646-1
;; => -Deja-DejaVu Math TeX Gyre-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ethiopic-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Roman-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Canadian Aboriginal-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Nabataean-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Hebrew-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Georgian-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK JP-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK HK-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK KR-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK SC-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cham-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Georgian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Sans Narrow-bold-normal-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK SC-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK TC-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-URW Bookman-semibold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK SC-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Hatran-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lydian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gurmukhi-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK TC-semibold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-ultrabold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bamum-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Sinhala-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tifinagh-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Myanmar-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Telugu-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Runic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-*-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Mro-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-ultrabold-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Display-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Sinhala-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Balinese-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ethiopic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Gurmukhi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK TC-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Hebrew-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ABAT-Cantarell-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Thai-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Kannada-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-C059-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK SC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tibetan-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-bold-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -ABAT-Cantarell-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-URW Bookman-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Canadian Aboriginal-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Georgian-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Meroitic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Gurmukhi UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Sinhala-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK SC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Symbols-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans-bold-oblique-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK TC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gujarati-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK HK-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-normal-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cuneiform-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil Slanted-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK SC-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans Mono-normal-oblique-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Lepcha-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gurmukhi-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-花園明朝A-normal-normal-normal-*-*-*-*-*-d-0-iso10646-1
;; => -GOOG-Noto Serif Ethiopic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-light-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thaana-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Lao-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans-bold-normal-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK JP-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK KR-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK JP-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Gurmukhi-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Old Persian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK KR-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Javanese-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Symbols-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lisu-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sundanese-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK HK-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Multani-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-C059-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ABAT-Cantarell-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Hebrew-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK KR-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sora Sompeng-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Serif-bold-italic-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bassa Vah-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Myanmar-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Caucasian Albanian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK SC-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-bold-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Mono-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Georgian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Myanmar-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Thai-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Elbasan-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Serif-normal-italic-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-normal-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Lao-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Hebrew-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Egyptian Hieroglyphs-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cherokee-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Sinhala-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans PhagsPa-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Lao-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Rejang-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Old Permic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Mono PS-normal-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Gurmukhi UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK SC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Naskh Arabic UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Telugu UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK TC-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Kannada-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-ultrabold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK JP-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thaana-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK KR-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-thin-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Miao-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Ethiopic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Serif-bold-normal-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Khmer-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Sans-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK KR-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK JP-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Hebrew-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-light-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Nastaliq Urdu-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Symbols-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Sinhala-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Canadian Aboriginal-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thaana-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ethiopic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Thai-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-thin-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK JP-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK HK-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK KR-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK JP-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Sans Narrow-bold-oblique-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK TC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-extralight-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Syloti Nagri-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Sans Narrow-normal-oblique-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK SC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thaana-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Oriya UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Armenian-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tibetan-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ogham-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Avestan-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK SC-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Brahmi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Armenian-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Carian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Coptic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Gothic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK HK-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK HK-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Glagolitic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-semibold-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Lao-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Khmer-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK TC-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Armenian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Symbols-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ugaritic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Kannada-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cham-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gurmukhi-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Pau Cin Hau-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Oriya-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Bengali-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Devanagari-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Deseret-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Georgian-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Osmanya-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Telugu-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Oriya-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Kannada-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Buhid-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Psalter Pahlavi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Kufi Arabic-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Telugu UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Yi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Georgian-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK TC-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Thai-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cherokee-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tagalog-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ethiopic-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-light-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Old South Arabian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Ethiopic-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-light-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Tai Viet-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Vai-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Lao-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans Mono-bold-oblique-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Kannada-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-normal-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Armenian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Oriya UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-light-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK SC-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK TC-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kayah Li-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -URW -D050000L-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-bold-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Serif Georgian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Manichaean-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK KR-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK HK-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans Mono-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK JP-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Thai-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Meetei Mayek-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans-normal-oblique-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK TC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Devanagari-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Hebrew-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Tamil-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil Slanted-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Z003-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans NKo-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil Slanted-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UFAS-Symbola-normal-normal-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Sans-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Takri-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Gujarati-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-semibold-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Modi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-semibold-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-normal-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Cham-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-C059-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Roman-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans New Tai Lue-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK JP-semibold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -URW -Standard Symbols PS-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tagbanwa-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK JP-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gujarati-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil Slanted-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-URW Bookman-semibold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-ultrabold-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans CJK TC-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Georgian-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tibetan-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Hebrew-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans-extralight-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Sinhala-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-P052-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Armenian-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Naskh Arabic-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-thin-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gurmukhi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Myanmar-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Naskh Arabic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Hebrew-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Shavian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Variable-extralight-italic-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Mono PS-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Syriac-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Kannada-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Symbols-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lycian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Imperial Aramaic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Armenian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-light-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gujarati-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-ultrabold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Gujarati UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Grantha-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Pahawh Hmong-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK JP-extralight-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Inscriptional Pahlavi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tai Le-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Telugu-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Myanmar-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ethiopic-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ABAT-Cantarell-extrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Ethiopic-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Ol Chiki-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Linear A-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Canadian Aboriginal-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Armenian-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Saurashtra-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Lao-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Myanmar-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sinhala UI-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil Slanted-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cherokee-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Display-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Armenian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Limbu-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Linear B-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Khmer-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK KR-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Palmyrene-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Kannada-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tibetan-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Serif-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-URW Gothic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-light-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Serif Display-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Duployan-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Sharada-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Inscriptional Parthian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-ultrabold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-ultrabold-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Serif Tamil-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Osage-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari UI-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Gujarati-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khojki-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Batak-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Ethiopic-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali UI-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK KR-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Sans-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-bold-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Serif Thai-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK TC-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Roman-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tirhuta-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Lao-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Hebrew-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Display-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Serif-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Mono PS-bold-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Sans Tamil UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Arabic-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Buginese-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kaithi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK KR-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -ADBO-Source Code Pro-semibold-normal-normal-*-*-*-*-*-m-0-iso10646-1
;; => -GOOG-Noto Serif Khmer-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-P052-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Georgian-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Serif-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Hebrew-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Old North Arabian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cherokee-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK KR-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tibetan-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-P052-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-bold-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK TC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif CJK KR-semibold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Khmer-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -PfEd-DejaVu Sans-normal-oblique-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Canadian Aboriginal-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-P052-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Symbols-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK SC-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Gujarati-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Newa-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK SC-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Tamil-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Lao-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari UI-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Math-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Georgian-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Malayalam-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-URW Gothic-semibold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tibetan-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Chakma-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Warang Citi-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -UKWN-Nimbus Sans Narrow-normal-normal-semicondensed-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam UI-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK KR-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK HK-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Music-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Kannada-thin-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Mono CJK JP-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif-normal-italic-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Cherokee-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Armenian-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Tamil Slanted-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Adlam-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Serif Ahom-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Bengali-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Georgian-bold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans CJK JP-ultrabold-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Devanagari-light-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -GOOG-Noto Sans Malayalam-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1
;; => -misc-fixed-medium-r-semicondensed--13-*-75-75-c-60-iso8859-1
;; => -misc-fixed-medium-r-semicondensed--13-*-100-100-c-60-iso8859-1


