run4:
	docker-compose run --rm python python parse3.py source.csv
run3:
	docker-compose run --rm python python parse2.py source.csv
run2:
	docker-compose run --rm python dictknife cat source.csv -o yaml
run:
	docker-compose run --rm python python parse.py source.csv
