# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields
)


class ArrayItem(Schema):
    null_value = fields.Field(allow_none=True)
    boolean = fields.Boolean()
    integer = fields.Integer()


class Object(Schema):
    key = fields.String(required=True)
    array = fields.List(fields.Nested('ArrayItem'), required=True)


class Top(Schema):
    json = fields.List(fields.String(), required=True)
    yaml = fields.List(fields.String(), required=True)
    object = fields.Nested('Object', required=True)
    paragraph = fields.String(required=True)
    content = fields.String(required=True)
