# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields
)


class ArrayItem(Schema):
    boolean = fields.Boolean()
    integer = fields.Integer()
    null_value = fields.Field(allow_none=True)


class Object(Schema):
    array = fields.List(fields.Nested('ArrayItem'))
    key = fields.String()


class Top(Schema):
    content = fields.String()
    json = fields.List(fields.String())
    object = fields.Nested('Object')
    paragraph = fields.String()
    yaml = fields.List(fields.String())
