# minimap ###
# *top
#   * json[]
#   * yaml[]
#   * object
#     * array[]
#       * arrayItem
definitions:
  json:
    type: array
    items:
      type: string
      example: slim and flexible
  arrayItem:
    type: object
    properties:
      null_value:
        type: any
        x-nullable: true
      boolean:
        type: boolean
        example: true
      integer:
        type: integer
        example: 1
  array:
    type: array
    items:
      $ref: '#/definitions/arrayItem'
  object:
    type: object
    properties:
      key:
        type: string
        example: value
      array:
        $ref: '#/definitions/array'
    required:
    - key
    - array
  top:
    type: object
    properties:
      json:
        $ref: '#/definitions/json'
      yaml:
        $ref: '#/definitions/json'
      object:
        $ref: '#/definitions/object'
      paragraph:
        type: string
        example: 'Blank lines denote

          paragraph breaks

          '
      content:
        type: string
        example: 'Or we

          can auto

          convert line breaks

          to save space'
    required:
    - json
    - yaml
    - object
    - paragraph
    - content
