definitions:
  json:
    type: array
    items:
      type: string
  yaml:
    type: array
    items:
      type: string
  arrayItem:
    type: object
    properties:
      null_value:
        type: any
        x-nullable: true
      boolean:
        type: boolean
      integer:
        type: integer
  array:
    type: array
    items:
      $ref: '#/definitions/arrayItem'
  object:
    type: object
    properties:
      key:
        type: string
      array:
        $ref: '#/definitions/array'
    required:
    - key
    - array
  top:
    type: object
    properties:
      json:
        $ref: '#/definitions/json'
      yaml:
        $ref: '#/definitions/yaml'
      object:
        $ref: '#/definitions/object'
      paragraph:
        type: string
      content:
        type: string
    required:
    - json
    - yaml
    - object
    - paragraph
    - content
