package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"m/model"
	"os"
)

// this file is generated by egoist.generators.clikit

// Option ...
type Option struct {
	Filename string   // for `-filename`
	Args     []string // cmd.Args
}

func main() {
	opt := &Option{}
	cmd := flag.NewFlagSet("cmd__load", flag.ContinueOnError)

	cmd.StringVar(&opt.Filename, "filename", "", "-")

	if err := cmd.Parse(os.Args[1:]); err != nil {
		if err != flag.ErrHelp {
			cmd.Usage()
		}
		os.Exit(1)
	}
	opt.Args = cmd.Args()
	if err := run(opt); err != nil {
		log.Fatalf("!!%+v", err)
	}
}

func run(opt *Option) error {
	f, err := os.Open(opt.Filename)
	if err != nil {
		return err
	}
	defer f.Close()

	var ob model.Article
	decoder := json.NewDecoder(f)
	if err := decoder.Decode(&ob); err != nil {
		return err
	}
	fmt.Printf("%#+v\n", ob)
	return nil
}
