export Addr ?= :44444
00:
	go run $(shell echo $@*/)main.go

# echo '{"target": "foo"}' | http --json POST :44444/api/hello
01:
	go run $(shell echo $@*/)main.go

# http :44444/api
02:
	go run $(shell echo $@*/)main.go
# http :44444/api
03:
	go run $(shell echo $@*/)main.go
# http :44444/api
04:
	go run $(shell echo $@*/)main.go
