r"""
generated by json2python-models v0.1.2 at Sat Oct 26 17:27:09 2019
command: /home/nao/.cache/pypoetry/virtualenvs/foo-py3.7/bin/json2models -m User ../data/person.json
"""
class User:
    name: str
    age: int

