// Automatically generated by MockGen. DO NOT EDIT!
// Source: ./foo.go

package mock_foo

import (
	. "github.com/podhmo/foo"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Foo interface
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *_MockFooRecorder
}

// Recorder for MockFoo (not exported)
type _MockFooRecorder struct {
	mock *MockFoo
}

func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &_MockFooRecorder{mock}
	return mock
}

func (_m *MockFoo) EXPECT() *_MockFooRecorder {
	return _m.recorder
}

func (_m *MockFoo) Foo() S {
	ret := _m.ctrl.Call(_m, "Foo")
	ret0, _ := ret[0].(S)
	return ret0
}

func (_mr *_MockFooRecorder) Foo() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Foo")
}
