default: 01 02 03 04 05 06 07 08

01:
	jsonknife separate --src 01*/schema.json --format json
02:
	jsonknife separate --src 02*/schema.json
03:
	jsonknife separate --src 03*/schema.yaml
04:
	jsonknife separate --src 04*/schema.yaml
05:
	jsonknife separate --src 05*/openapi.yaml
06:
	jsonknife separate --src 06*/schema.json -o json
07:
	jsonknife --debug separate --src 07*/main.yaml
08:
	jsonknife separate --src 08*/schema.json
