default: 01 02 03 04 05 06

01:
	jsonknife separate --src 01*/schema.json
02:
	jsonknife separate --src 02*/schema.json
03:
	jsonknife separate --src 03*/schema.yaml
04:
	jsonknife separate --src 04*/schema.yaml
05:
	jsonknife separate --src 05*/openapi.yaml
06:
	jsonknife separate --src 06*/schema.json
