default: 01 02 03 04 05 06

01:
	python -m dictknife.jsonknife.separate 01*/schema.json
02:
	python -m dictknife.jsonknife.separate 02*/schema.json
03:
	python -m dictknife.jsonknife.separate 03*/schema.yaml
04:
	python -m dictknife.jsonknife.separate 04*/schema.yaml
05:
	python -m dictknife.jsonknife.separate 05*/openapi.yaml
06:
	python -m dictknife.jsonknife.separate 06*/schema.json
