00serve:
	python 00serve.py --connection-name x.json
00client:
	python 00client.py --connection-name x.json

01serve:
	python 01serve.py --connection-name x.json
01client:
	python 01client.py --connection-name x.json
