00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)
	python $(shell echo $@*.py) --expose
04:
	python $(shell echo $@*/)cli.py -h
