00:
	go run $(shell echo $@*/)main.go
01:
	go run $(shell echo $@*/)main.go
02:
	go run $(shell echo $@*/)main.go
# broken
03:
	go run $(shell echo $@*/)main.go
04:
	go run $(shell echo $@*/)main.go
# broken
05:
	go run $(shell echo $@*/)main.go
