default: 6

0:
	mypy --strict 00*.py
1:
	mypy --strict 01*.py
2:
	mypy --strict 02*.py
3:
	mypy --strict 03*.py
4:
	mypy --strict 04*.py
5:
	mypy --strict 05*.py
6:
	mypy --strict 06*.py
7:
	mypy --strict 07*.py
