default:
	 NAME=foo AGE=20 dictknife concat person.yaml.env --dst person.yaml
	 NAME=foo AGE=20 dictknife concat person.json.env --dst person.json
	 NAME=foo AGE=20 dictknife concat person2.yaml.env --dst person2.yaml
