ok:
	python runner.py python 00run.py
ng:
	NG=1 python runner.py python 00run.py

interrupt:
	python runner.py --waittime=3 python 00run.py

01:
	python runner.py python 01run.py
02:
	python runner.py python 02run.py
10:
	python runner.py python 10run.py

export PYTHONPATH := ../example_cython/mysleep
11:
	python runner.py python 11run.py
20:
	python 20.py
21:
	python 21.py
