00:
	go run $(shell echo $@*/)main.go --name world
01:
	go run $(shell echo $@*/)main.go --target $(shell echo 00*/)main.go:Run
02:
	go run $(shell echo $@*/)main.go
03:
	go run $(shell echo $@*/)main.go
04:
	go run $(shell echo $@*/)main.go
