package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Nperson nperson
// swagger:model nperson
type Nperson struct {
}

// Validate validates this nperson
func (m *Nperson) Validate(formats strfmt.Registry) error {
	return nil
}
