server:
	python 00hello.py

200:
	http GET :8080/

404:
	http GET :8080/404

json404:
	http GET :8080/404 Accept:application/json

500:
	http GET :8080/500
json500:
	http GET :8080/500 Accept:application/json
