00:
	rm -rf $@filekit
	mkdir -p $@filekit
	cd $@filekit && egoist init filekit && python definitions.py generate

01:
	rm -rf $@dirkit
	mkdir -p $@dirkit
	cd $@dirkit && egoist init dirkit && python definitions.py generate
