default: 00 01 02

00:
	python -u -X importtime $(shell echo $@*.py) 2>&1 | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
01:
	python -u -X importtime $(shell echo $@*.py) 2>&1 | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
02:
	python -u -X importtime $(shell echo $@*.py) 2>&1 | tee $(patsubst %.py,%.output,$(shell echo $@*.py))
