title: App Config
definitions:
  XXXAPI:
    title: XXXAPI
    type: object
    properties:
      token:
        title: Token
        type: string
    required:
    - token
  Config:
    title: Config
    type: object
    properties:
      port:
        title: Port
        type: integer
      logLevel:
        title: Loglevel
        anyOf:
        - const: debug
          type: string
        - const: info
          type: string
        - const: warn
          type: string
        - const: error
          type: string
        - const: critical
          type: string
      secondary:
        $ref: '#/definitions/Config'
      xxxAPI:
        $ref: '#/definitions/XXXAPI'
    required:
    - port
    - logLevel
$ref: '#/definitions/Config'
