00:
	go run $(shell echo $@*/)main.go
01:
	go run $(shell echo $@*/)main.go -db $(shell echo $@*/)sample.db
02:
	$(MAKE) -C $(shell echo $@*/)
03:
	ADDR=:8888 go run $(shell echo $@*/)main.go
04:
	ADDR=:8888 go run $(shell echo $@*/)main.go
