00:
	cat $(shell echo $@*messages) | python -m monogusa.cli $(shell echo $@*.py) read
01:
	cat $(shell echo $@*messages) | python -m monogusa.cli $(shell echo $@*.py) read
	@echo ---
	python -m monogusa.cli $(shell echo $@*.py) read
