00:
	python 00*.py 2>&1 | tee 00.output
01:
	python 01*.py 2>&1 | tee 01.output
02:
	python 02*.py 2>&1 | tee 02.output
03:
	python 03*.py 2>&1 | tee 03.output
04:
	python 04*.py 2>&1 | tee 04.output
05:
	python 05*.py 2>&1 | tee 05.output
06:
	python 06*.py 2>&1 | tee 06.output
07:
	python 07*.py 2>&1 | tee 07.output
08:
	python 08*.py 2>&1 | tee 08.output
09:
	python 09*.py 2>&1 | tee 09.output
10:
	python 10*.py 2>&1 | tee 10.output
