default: 00
00:
	go run $(wildcard 00*)/main.go
01:
	go run $(wildcard 01*)/main.go
02:
	go run $(wildcard 02*)/main.go
03:
	go run $(wildcard 03*)/main.go
04:
	go run $(wildcard 04*)/main.go
05:
	go run $(wildcard 05*)/main.go
