00:
	DEBUG=1 python $@*.py main
01:
	DEBUG=1 python $@*.py main
02:
	DEBUG=1 python $@*.py main
03:
	LOGGING_FORMAT="%(process)d	%(levelname)s:%(message)s" DEBUG=1 python $@*.py main
04:
	DEBUG=1 python $@*.py main
05:
	DEBUG=1 python $@*.py main
06:
	DEBUG=1 python $@*.py main
