00:
	cd $(shell echo $@*/) && go test
01:
#	go run $(shell echo $@*/)*
	cd $(shell echo $@*/) && go test
02:
	go run $(shell echo $@*/)main.go
03:
	go run $(shell echo $@*/)main.go
04:
	go run $(shell echo $@*/)main.go
05:
	go run $(shell echo $@*/)main.go
