00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	@DISCORD_API_TOKEN=$(shell jqfpy 'get("discord/api-token")' ~/.config/monogusa/config.json -r) python $(shell echo $@*.py)
