00:
	(cd 00*&& python main.py)
	(cd 00*&& prefix=bye python main.py)
	(cd 00*&& PREFIX=bye python main.py)
	echo ----
	(cd 00*&& python main2.py)
	(cd 00*&& prefix=bye python main2.py)
	(cd 00*&& PREFIX=bye python main2.py)

01:
	(cd 01*&& python main2.py)
	(cd 01*&& python main3.py)
02:
	(cd 02*&& python main*.py)
	(cd 02*&& prefix=bye python main*.py)

03:
	(cd 03*&& python main*.py)
	(cd 03*&& python sub/main*.py)
	(cd 03*&& python sub2/main*.py)
