default:
	python parse.py a0.yaml

00:
	python $@*.py person.json
01:
	python $@*.py person.json
02:
	python $@*.py person.json
03:
	python $@*.py person.json
04:
	python $@*.py person.json
05:
	python $@*.py person.json
06:
	python $@*.py person.json
07:
	python $@*.py a0.yaml
08:
	python $@*.py a0.yaml
09:
	python $@*.py a0.yaml
10:
	python $@*.py ng-pair.yaml
11:
	python $@*.py ng-pair.yaml
12:
#	python $@*.py ng-main.yaml
#	python $@*.py ng-user.yaml
#	python $@*.py a1.yaml
	python $@*.py ng-pair.yaml
13:
	python $@*.py rec.yaml
	python $@*.py ng-main.yaml
	python $@*.py ng-user.yaml
	python $@*.py a1.yaml
	python $@*.py ng-pair.yaml
14:
	python $@*.py ng-main.yaml
15:
	python $@*.py rec.yaml
	python $@*.py ng-main.yaml
	python $@*.py ng-user.yaml
	python $@*.py a1.yaml
	python $@*.py ng-pair.yaml

