default:
	python parse.py a0.yaml

00:
	python $@*.py person.json
01:
	python $@*.py person.json
02:
	python $@*.py person.json
03:
	python $@*.py person.json
04:
	python $@*.py person.json
05:
	python $@*.py person.json
06:
	python $@*.py person.json
07:
	python $@*.py a0.yaml
08:
	python $@*.py a0.yaml
09:
	python $@*.py a0.yaml
10:
	python $@*.py ng-pair.yaml
11:
	python $@*.py ng-pair.yaml
