default:
	python parse.py person.json

00:
	python $@*.py person.json
01:
	python $@*.py person.json
02:
	python $@*.py person.json
03:
	python $@*.py person.json
04:
	python $@*.py person.json
05:
	python $@*.py person.json
06:
	python $@*.py person.json
07:
	python $@*.py user.yaml
