00:
	go run $(shell echo $@*/)main.go foo -enable -name=joe a1 a2
	go run $(shell echo $@*/)main.go bar -level 8 a1
	# go run $(shell echo $@*/)main.go bar -enable a1
	go run $(shell echo $@*/)main.go -help
