00:
	python $(shell echo $@*.py)
	mypy --strict  $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
	mypy --strict  $(shell echo $@*.py)
02:
	mypy --strict  $(shell echo $@*.py)
	python $(shell echo $@*.py)
03:
	mypy --strict  $(shell echo $@*.py)
	python $(shell echo $@*.py)
