from prestring.text import Module
m = Module(indent='\t')
m.stmt('package main')
m.sep()
m.stmt('import (')
with m.scope():
	m.stmt('"log"')
	m.stmt('"net/http"')
	m.stmt('"os"')
	m.sep()
	m.stmt('"github.com/gin-gonic/gin"')
	m.stmt('_ "github.com/heroku/x/hmetrics/onload"')
m.stmt(')')
m.sep()
m.stmt('func main() {')
with m.scope():
	m.stmt('port := os.Getenv("PORT")')
	m.sep()
	m.stmt('if port == "" {')
	with m.scope():
		m.stmt('log.Fatal("$PORT must be set")')
	m.stmt('}')
	m.sep()
	m.stmt('router := gin.New()')
	m.stmt('router.Use(gin.Logger())')
	m.stmt('router.LoadHTMLGlob("templates/*.tmpl.html")')
	m.stmt('router.Static("/static", "static")')
	m.sep()
	m.stmt('router.GET("/", func(c *gin.Context) {')
	with m.scope():
		m.stmt('c.HTML(http.StatusOK, "index.tmpl.html", nil)')
	m.stmt('})')
	m.sep()
	m.stmt('router.Run(":" + port)')
m.stmt('}')
print(m)
