00:
	python $(shell echo $@*.py)

01:
	DEBUG=1 python $(shell echo $@*.py) run
02:
	DEBUG=1 python $(shell echo $@*.py) run
03:
	DEBUG=1 python $(shell echo $@*.py) run
04:
	DEBUG=1 python $(shell echo $@*.py) run
