default: 00 01 02 03 04 05

00:
	dictknife diff 00{a,b}.json > 00.diff
	dictknife diff --normalize 00{a,b}.json > 00.normalized.diff
01:
	dictknife diff 01{a,b}.json > 01.diff
	dictknife diff --normalize 01{a,b}.json > 01.normalized.diff
02:
	dictknife diff 02{a,b}.json > 02.diff
	dictknife diff --normalize 02{a,b}.json > 02.normalized.diff
03:
	dictknife diff 03{a,b}.json > 03.diff
	dictknife diff --normalize 03{a,b}.json > 03.normalized.diff
04:
	dictknife diff 04{a,b}.json > 04.diff
	dictknife diff --normalize 04{a,b}.json > 04.normalized.diff
05:
	dictknife diff 05{a,b}.json > 05.diff
	dictknife diff --normalize 05{a,b}.json > 05.normalized.diff
