package main

import (
	"flag"
	"os"
	"log"
	"fmt"
)

// this file is generated by egoist.generators.clikit

// Option ...
type Option struct {
	Name string // for `-name`
	Content string // for `-content`
	Args []string // cmd.Args
}


func main() {
	opt := &Option{}
	cmd := flag.NewFlagSet("cmd__hello", flag.ContinueOnError)

	cmd.StringVar(&opt.Name, "name", "", "-")
	cmd.StringVar(&opt.Content, "content", "", "-")

	if err := cmd.Parse(os.Args[1:]); err != nil {
		if err != flag.ErrHelp {
			cmd.Usage()
		}
		os.Exit(1)
	}
	opt.Args = cmd.Args()
	if err := run(opt); err != nil {
		log.Fatalf("!!%+v", err)
	}
}

func run(opt *Option) error {
	fmt.Printf("hello")
	return nil
}