consumes:
- application/json
info:
  title: 02bug
  version: 0.1.0

definitions:
  dateText:
    description: my date text
    type: string
    format: date

paths:
  /ng:
    post:
      description: ng
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/dateText"
      responses:
        200:
          description: ok
          schema:
            type: string
            format: date
  /ng2:
    post:
      description: ng
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: string
            format: date
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/dateText"
  /ok:
    post:
      description: ok
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: string
            format: date
      responses:
        200:
          description: ok
          schema:
            type: string
            format: date


produces:
- application/json
schemes:
- http
swagger: "2.0"
