00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python -m handofcats $(shell echo $@*.py):hello
03:
	python $(shell echo $@*.py)
04:
	python -m handofcats --cont=dump.py:dump $(shell echo $@*.py):hello
05:
	python $(shell echo $@*.py)
