workdir = $(shell echo $@*/)

00:
	go run $(workdir)main.go | tee $(workdir)openapi.json
01:
	go run $(workdir)main.go | tee $(workdir)openapi.json
02:
	go run $(workdir)main.go | tee $(workdir)openapi.json
