package models

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// XUser x user
// swagger:model xUser
type XUser struct {
	User
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *XUser) UnmarshalJSON(raw []byte) error {

	var aO0 User
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.User = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m XUser) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.User)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this x user
func (m *XUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.User.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
