00:
	go run $(shell echo $@*/)main.go
01:
	go run $(shell echo $@*/)main.go
02:
	cd $(shell echo $@*/) && go test -bench . -benchmem
03:
	go run $(shell echo $@*/)main.go
04:
	go run $(shell echo $@*/)main.go
05:
	go run $(shell echo $@*/)main.go
06:
	go run $(shell echo $@*/)main.go
07:
	go run $(shell echo $@*/)main.go
08:
	go run $(shell echo $@*/)main.go
09:
	go run $(shell echo $@*/)main.go
10:
	go run $(shell echo $@*/)main.go

