default: 00 01 02 03

00:
	kamidana -a kamidana.additionals.reader 00rst.j2 > 00.rst
01:
	kamidana --data data.json -e do 01json.j2 > 01.json
02:
	kamidana -a kamidana.additionals.reader 02md.j2 > 02.md
03:
	kamidana -a kamidana.additionals.reader 03rst.j2 > 03.rst
