package main

import (
	"fmt"
	"log"
	"os"
	"runtime"
	"strings"

	"github.com/podhmo/handmade/script"
)

func main() {
	if err := run(); err != nil {
		log.Fatalf("!! %+v", err)
	}
}
func run() error {
	emitWith := func(fn func(m *script.Module)) {
		m := script.NewGoModule()
		fn(m)
		o, err := script.Encode(m)
		if err != nil {
			panic(err)
		}
		fmt.Print(o)
	}
	emitWith(func(m *script.Module) {
		m.Format("// hello")
	})
	emitWith(func(m *script.Module) {
		m.Capture(func(f *runtime.Func, pc uintptr) string {
			filename, lineno := f.FileLine(pc)
			cwd, _ := os.Getwd()
			filename = strings.Replace(filename, cwd, ".", 1)
			return fmt.Sprintf("// generated by %s:%d", filename, lineno)
		})
		m.Line(`func Hello(target string) string {`)
		m.Indent(func() {
			m.Line(`return fmt.Sprintf("hello %s", target)`)
		})
		m.Line(`}`)
	})
	return nil
}
