export PYTHONBREAKPOINT=ipdb.set_trace
URL ?= https://docs.google.com/spreadsheets/d/18fXVSZg_z7wNsGm0SaLHHftdI7MB_r59NnAGZ-VxY-s/edit

00:
	python 00*.py ${URL}
01:
	python 01*.py ${URL}
02:
	python 02*.py ${URL}
