00: outdir = 00out
00:
	rm -rf ${outdir}
	cookiecutter hello --no-input -o ${outdir}
01: outdir = 01out
01:
	rm -rf ${outdir}
	cookiecutter with_extra_context --no-input -o ${outdir} project_name=OVERRIDE
02: outdir = 02out
02:
	rm -rf ${outdir}
	cookiecutter with_additional_modules --no-input -o ${outdir}
