00: outdir = 00out
00:
	rm -rf ${outdir}
	cookiecutter -v hello --no-input -o ${outdir}
01: outdir = 01out
01:
	rm -rf ${outdir}
	cookiecutter -v with_extra_context --no-input -o ${outdir} project_name=OVERRIDE
02: outdir = 02out
02:
	rm -rf ${outdir}
	cookiecutter -v with_additional_modules --no-input -o ${outdir}
03: outdir = 03out
03:
	rm -rf ${outdir}
	cookiecutter -v with_additional_modules2 --no-input -o ${outdir}
04: outdir = 04out
04:
	rm -rf ${outdir}
	cookiecutter -v with_additional_modules3 --no-input -o ${outdir}
