default: o1 o2 o3

o1:
	~/.emacs.d/.python-environments/default/bin/jediepcserver-fake
o2: # ok
	VIRTUAL_ENV=~/venvs/my 	~/.emacs.d/.python-environments/default/bin/jediepcserver-fake
o3:
	VIRTUAL_ENV=~/.emacs.d/.python-environments/default  	~/.emacs.d/.python-environments/default/bin/jediepcserver-fake
o4:
	~/.emacs.d/.python-environments/default/bin/jediepcserver-fake --virtual-env=~/venvs/my
