00:
	firestarter run --config 00config.toml
00-client:
	python 00*-client.py
00-serve:
	python 00*-server.py

01:
	python 01*-client.py
01-serve:
	python 01*-server.py

02-ventilator:
	python 02*-ventilator.py
02-worker:
	python 02*-worker.py
02-sink:
	python 02*-sink.py

setup:
	which firestarter || cargo install firestarter
