DB ?= pokemon/pokemon.d

00:
	go run $(shell echo $@*/)main.go
01:
	DB=$(DB) go run $(shell echo $@*/)main.go
02:
	DB=$(DB) go run $(shell echo $@*/)main.go
03:
	DB=$(DB) go run $(shell echo $@*/)main.go
04:
	go run $(shell echo $@*/)main.go
05:
	go run $(shell echo $@*/)main.go
