00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	cat messages | python $(shell echo $@*.py)
03:
	cat messages | python $(shell echo $@*.py)
04:
	cat messages | python $(shell echo $@*.py)
