00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	time python $(shell echo $@*.py)
03:
	time python $(shell echo $@*.py)
04:
	time python $(shell echo $@*.py)
05:
	time python $(shell echo $@*.py)

