00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	time python $(shell echo $@*.py)
03:
	time python $(shell echo $@*.py)
04:
	time python $(shell echo $@*.py)
05:
	time python $(shell echo $@*.py)
06:
	time python $(shell echo $@*.py)
07:
	time python $(shell echo $@*.py)
08:
	time python $(shell echo $@*.py)
09:
	time python $(shell echo $@*.py)
10:
	time python $(shell echo $@*.py)

