00:
	open $(shell echo $@*.html)
01:
	open $(shell echo $@*.html)
02:
	open $(shell echo $@*.html)
03:
	open $(shell echo $@*.html)
04:
	open $(shell echo $@*.html)
05:
	open $(shell echo $@*.html)
06:
	open $(shell echo $@*.html)
07:
	open $(shell echo $@*.html)
07:
	open $(shell echo $@*.html)
08:
	open $(shell echo $@*.html)
09:
	open $(shell echo $@*.html)
10:
	open $(shell echo $@*.html)
