export GOPACKAGESDEBUG := 1

00:
	go run $(shell echo $@*/)main.go
01:
	go run $(shell echo $@*/)main.go
02:
	go run $(shell echo $@*/)main.go
03:
	go run $(shell echo $@*/)main.go
04:
	go test -v ./$(shell echo $@*/)
# name
05:
	go run $(shell echo $@*/)main.go ./database
# name + import
06:
	go run $(shell echo $@*/)main.go ./database
# name + types
07:
	go run $(shell echo $@*/)main.go ./database
# name + files
08:
	go run $(shell echo $@*/)main.go ./database
