00:
	python -m monogusa.cli commands.py hello
01:
	python gen.py
02:
	python -m monogusa.web commands.py --with-gen
03:
# dictknife mkdict name=world | http --json POST :33333/hello
	python web.py --port=33333
