00:
	DEBUG=1 LOGGING_TIME=relative python $(shell echo $@*.py)
01:
	DEBUG=1 LOGGING_TIME=relative python $(shell echo $@*.py)
02:
	DEBUG=1 LOGGING_TIME=relative python $(shell echo $@*.py)
03:
	DEBUG=1 python $(shell echo $@*.py)
04:
	DEBUG=1 python $(shell echo $@*.py)
05:
	DEBUG=1 python $(shell echo $@*.py)
06:
	DEBUG=1 LOGGING_TIME=relative python $(shell echo $@*.py)
