00:
	go run $(shell echo $@*/)main.go $(shell echo $@*/)
01:
	go run $(shell echo $@*/)main.go
02:
	go run $(shell echo $@*/)main.go
03:
	go run $(shell echo $@*/)main.go
04:
	go run $(shell echo $@*/)main.go $(shell echo $@*/)
05:
	go run $(shell echo $@*/)main.go
06:
	go run $(shell echo $@*/)main.go $(shell echo $@*/)
07:
	go run $(shell echo $@*/)main.go $(shell echo $@*/)

