swagger: "2.0"
info:
  title: Tmp
  version: 0.1.0

definitions:
  positiveInteger:
    type: integer
    minimum: 0
  person:
    description: person
    type:
      object
    properties:
      name:
        type: string
      age:
        $ref: "#definitions/positiveInteger"
    required:
      - name

paths:
  /:
    get:
      operationId: index
      description: index
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: "#/definitions/person"

