default: 00 01 02

00:
	rm -f 00.output
	bash -c 'time go run 00*.go' >> 00.output 2>&1
	bash -c 'time go run 00*.go' >> 00.output 2>&1
	bash -c 'time go run 00*.go' >> 00.output 2>&1
01:
	rm -f 01.output
	bash -c 'time go run 01*.go' >> 01.output 2>&1
	bash -c 'time go run 01*.go' >> 01.output 2>&1
	bash -c 'time go run 01*.go' >> 01.output 2>&1
02:
	rm -f 02.output
	bash -c 'time go run 02*.go' >> 02.output 2>&1
	bash -c 'time go run 02*.go' >> 02.output 2>&1
	bash -c 'time go run 02*.go' >> 02.output 2>&1
