00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)
04:
	python $(shell echo $@*.py)
05:
	diff -u 03*.py 04*.py > 05-0304.diff
06:
	python $(shell echo $@*.py)
07:
	diff -u 04*.py 06*.py > 07-0406.diff
