00:
	python $(shell echo $@*/)definitions.py generate
	go run $(shell echo $@*/)cmd/hello/main.go
01:
	python $(shell echo $@*/)definitions.py generate
	go run $(shell echo $@*/)cmd/hello/main.go
02:
	python $(shell echo $@*/)definitions.py generate
