00:
	python $@*.py
01:
	python $@*.py
02:
	python $@*.py
03:
	python $@*.py
04:
	python $@*.py
05:
	python $@*.py
06:
	swagger-marshmallow-codegen $@*.yaml
07:
	swagger-marshmallow-codegen --full $@*.yaml
08:
	swagger-marshmallow-codegen $@*.yaml
09:
	swagger-marshmallow-codegen $@*.yaml > _$@.py
	python _$@.py
