00:
	python 00colorful.py sample.csv
	python 00colorful.py TEST_STOCK.csv

setup:
	wget https://gist.githubusercontent.com/RobVanGroenewoud/ba89ad7684df8cefe5c183adb498cc65/raw/f2eec6d2cb89f5d779e16b28ed0dab89d738ba96/sample.csv
	# from https://qiita.com/motoki1990/items/0274d8bcf1a97fe4a869
