version: '3'

# https://hub.docker.com/_/postgres 
# accessing:
# psql -h localhost -p 5432 
services:
  db:
    image: postgres:14.0
    restart: always
    hostname: db
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testtest
      # POSTGRES_DB: sample
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    networks:
      - db-net
    

volumes:
  db-data:

networks:
  db-net:
    driver: bridge