package main

import (
	"bytes"
	"encoding/json"
	"log"

	"github.com/k0kubun/pp"
	"github.com/podhmo/maperr"
)

// this file is generated by egoist.generators.structkit

type Person struct {
	Name       string                       `json:"name"`
	Age        int                          `json:"age"`
	Followings [][]Person                   `json:"followings"`
	Groups     map[string]map[string]Person `json:"groups"`
}

func (p *Person) UnmarshalJSON(b []byte) error {
	var err *maperr.Error

	// loading internal data
	var inner struct {
		Name       *string                       `json:"name"`       // required
		Age        *int                          `json:"age"`        // required
		Followings *[][]Person                   `json:"followings"` // required
		Groups     *map[string]map[string]Person `json:"groups"`     // required
	}
	if rawErr := json.Unmarshal(b, &inner); rawErr != nil {
		return err.AddSummary(rawErr.Error())
	}

	// binding field value and required check
	{
		if inner.Name != nil {
			p.Name = *inner.Name
		} else {
			err = err.Add("name", maperr.Message{Text: "required"})
		}
		if inner.Age != nil {
			p.Age = *inner.Age
		} else {
			err = err.Add("age", maperr.Message{Text: "required"})
		}
		if inner.Followings != nil {
			p.Followings = *inner.Followings
		} else {
			err = err.Add("followings", maperr.Message{Text: "required"})
		}
		if inner.Groups != nil {
			p.Groups = *inner.Groups
		} else {
			err = err.Add("groups", maperr.Message{Text: "required"})
		}
	}

	return err.Untyped()
}

type Person2 struct {
	Name string `json:"name"`
}

func (p *Person2) UnmarshalJSON(b []byte) error {
	var err *maperr.Error

	// loading internal data
	var inner struct {
		Name *string `json:"name"` // required
	}
	if rawErr := json.Unmarshal(b, &inner); rawErr != nil {
		return err.AddSummary(rawErr.Error())
	}

	// binding field value and required check
	{
		if inner.Name != nil {
			p.Name = *inner.Name
		} else {
			err = err.Add("name", maperr.Message{Text: "required"})
		}
	}

	return err.Untyped()
}

func main() {
	b := bytes.NewBufferString(`{"name": "foo","age": 20, "followings": [[{"name": "foo","age": 20, "followings": [], "groups": {}}]], "groups": {}}`)
	decoder := json.NewDecoder(b)
	var p Person
	if err := decoder.Decode(&p); err != nil {
		log.Fatalf("!! %+v", err)
	}
	pp.Println(p)
}
