00:
	TSX=./$@client.tsx deno run -A jsr:@podhmo/glue@0.2.1 serve --port 8080 ./main.ts
01:
	TSX=./$@client.tsx deno run -A jsr:@podhmo/glue@0.2.1 serve --port 8080 ./main.ts --development
02:
	TSX=./$@client.tsx deno run -A jsr:@podhmo/glue@0.2.1 serve --port 8080 ./main.ts