start:
	ioknife too \
 --cmd "npm run start" \
 --cmd "go run reverseproxy/main.go 55555 http://localhost:44444 ./static"\
 
	# http :55555/static/00hello/index.jsx
	# xdg-open http://localhost:55555/static/00hello
browse:
	xdg-open http://localhost:44444
