00:
	python $(shell echo $@*.py)
01:
	python $(shell echo $@*.py)
02:
	python $(shell echo $@*.py)
03:
	python $(shell echo $@*.py)
04:
	python $(shell echo $@*/)main.py
05:
	python $(shell echo $@*/)onefile.py
06:
	python $(shell echo $@*/)bundle.py
	python $(shell echo $@*/)main.py
