00:
	python 00*.py
02:
	ioknife too --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py"
03:
	ioknife too --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py" --cmd "python -u gen.py"


