// Code generated by "stringer -type Pill"; DO NOT EDIT.
package pill

import (
	"fmt"
)

// String :
func (x Pill) String() string {
	switch x {
	case Placebo:
		return "Placebo"
	case Aspirin:
		return "Aspirin"
	case Ibuprofen:
		return "Ibuprofen"
	case Paracetamol:
		return "Paracetamol"
	case Acetaminophen:
		return "Acetaminophen"
	default:
		return fmt.Sprintf("Pill(%q)", x)
	}
}
