00:
	go run $(shell echo $@*)/main.go
01:
	go run $(shell echo $@*)/main.go
02:
	go run $(shell echo $@*)/main.go
03:
	cd  $(shell echo $@*) && go run main.go
04:
	cd  $(shell echo $@*) && go run main.go
05:
	cd  $(shell echo $@*) && go run main.go
06:
	cd  $(shell echo $@*) && go run main.go
