import pkgutil
import apistar

for mo in pkgutil.walk_packages(apistar.__path__, prefix="apistar."):
    print(mo.name)

# apistar.client
# apistar.client.auth
# apistar.client.client
# apistar.client.transports
# apistar.client.utils
# apistar.codecs
# apistar.codecs.base
# apistar.codecs.config
# apistar.codecs.download
# apistar.codecs.jsondata
# apistar.codecs.jsonschema
# apistar.codecs.multipart
# apistar.codecs.openapi
# apistar.codecs.swagger
# apistar.codecs.text
# apistar.codecs.urlencoded
# apistar.compat
# apistar.conneg
# apistar.document
# apistar.exceptions
# apistar.formats
# apistar.http
# apistar.main
# apistar.parse
# apistar.server
# apistar.server.adapters
# apistar.server.app
# apistar.server.asgi
# apistar.server.components
# apistar.server.core
# apistar.server.handlers
# apistar.server.injector
# apistar.server.router
# apistar.server.staticfiles
# apistar.server.templates
# apistar.server.validation
# apistar.server.wsgi
# apistar.test
# apistar.tokenize
# apistar.tokenize.tokenize_json
# apistar.tokenize.tokenize_yaml
# apistar.tokenize.tokens
# apistar.types
# apistar.utils
# apistar.validators
