00:
	make -C $(shell echo $@*/)
01:
	make -C $(shell echo $@*/)

10:
	go run $(shell echo $@*/)main.go
11:
	go run $(shell echo $@*/)main.go
12:
	go run $(shell echo $@*/)main.go
13:
	go run $(shell echo $@*/)main.go
14:
	go run $(shell echo $@*/)main.go
# http /swagger

20:
	go run $(shell echo $@*/)main.go
21:
	go run $(shell echo $@*/)main.go
