00:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
01:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
02:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
03:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
04:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
05:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
06:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py) run
07:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py) run
