00:
	python 00*.py
01:
	python 01*.py
02:
	python 02*.py --name=foo
03:
	python 03*.py --config 03config.yaml --name=foo
	python 03*.py --config 03config.yaml
04:
	python 04*.py --config 04config.yaml
