00:
	cd $(shell echo $@*/) && terraform apply -auto-approve
01:
	cd $(shell echo $@*/) && terraform init && terraform apply -auto-approve
02:
	cd $(shell echo $@*/) && terraform init && terraform apply -auto-approve
03:
	cd $(shell echo $@*/) && terraform init && terraform apply -auto-approve
