default: 00 01 02 03 04
00:
	python 00*.py --src src/main.yaml
01:
	python 01*.py --src src/main.yaml
02:
	python 02*.py --src src/main.yaml
03:
	python 03*.py --src src/main.yaml
04:
	python 04*.py --src src/main.yaml
